spring.output.ansi.enabled=always
grpc.server.port=59091
collector.kafka.producer.bootstrap-servers=localhost:9092
collector.kafka.producer.key.serializer=org.apache.kafka.common.serialization.StringSerializer
collector.kafka.producer.value.serializer=ru.yandex.practicum.telemetry.collector.configuration.AvroSerializer
collector.kafka.producer.topics.sensors-events=telemetry.sensors.v1
collector.kafka.producer.topics.hubs-events=telemetry.hubs.v1
logging.level.ru.practicum=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.apache.kafka=DEBUG
logging.level.org.apache.http=DEBUG