aggregator.kafka.producer-properties.bootstrap-servers=localhost:9092
aggregator.kafka.producer-properties.key-serializer=org.apache.kafka.common.serialization.StringSerializer
aggregator.kafka.producer-properties.value-serializer=ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
aggregator.kafka.consumer-properties.bootstrap-servers=localhost:9092
aggregator.kafka.consumer-properties.group-id=aggregator-group
aggregator.kafka.consumer-properties.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
aggregator.kafka.consumer-properties.value-deserializer=ru.yandex.practicum.kafka.deserializer.SensorEventDeserializer
aggregator.kafka.topics.sensors-events=telemetry.sensors.v1
aggregator.kafka.topics.snapshots=telemetry.snapshots.v1
logging.level.ru.practicum=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.apache.kafka=DEBUG
logging.level.org.apache.http=DEBUG