grpc.client.hub-router.address=static://localhost:59090
grpc.client.hub-router.enableKeepAlive=true
grpc.client.hub-router.keepAliveWithoutCalls=true
grpc.client.hub-router.negotiationType=plaintext

analyzer.kafka.hub.consumer-topics=telemetry.hubs.v1
analyzer.kafka.hub.bootstrap-server=localhost:9092
analyzer.kafka.hub.group-id=analyzer-snapshot
analyzer.kafka.snapshot.consumer-topics=telemetry.snapshots.v1
analyzer.kafka.snapshot.bootstrap-server=localhost:9092
analyzer.kafka.snapshot.group-id=snapshot-processor

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/analyzer
spring.datasource.username=analyzer
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.output.ansi.enabled=always

logging.level.ru.practicum=INFO
logging.level.org.springframework.web=ERROR
logging.level.org.apache.kafka=ERROR
logging.level.org.apache.http=ERROR